server {
    # Écoute sur le port 443 en HTTPS uniquement
    listen      443 ssl;
    listen      [::]:443 ssl;

    # Nom de domaine du serveur — doit correspondre à DOMAIN_NAME dans .env
    server_name abbouras.42.fr;

    # Chemin vers le certificat TLS et la clé privée générés dans le Dockerfile
    ssl_certificate     /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    # Autorise uniquement TLSv1.2 et TLSv1.3 — les versions antérieures sont interdites par le sujet
    ssl_protocols TLSv1.2 TLSv1.3;

    # Dossier racine où sont stockés les fichiers WordPress
    # Ce dossier est partagé avec le conteneur WordPress via le volume wordpress_data
    root  /var/www/html;

    # Fichier index par défaut
    index index.php index.html;

    location / {
        # Essaie de servir le fichier demandé, sinon redirige vers index.php
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        # Passe les fichiers PHP à php-fpm via FastCGI
        # "wordpress" est le nom DNS du conteneur WordPress dans le réseau Docker
        fastcgi_pass  wordpress:9000;

        # Fichier index PHP par défaut
        fastcgi_index index.php;

        # Paramètres FastCGI standard requis par WordPress
        include       fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
